### ISSUE TITLE
How will this work?

### ISSUE THREAD

**Issue by ChopsKingsland** [HomeKidd/HomeKit-MagicHome-LED-controller-Elgato-Eve-Light-Strip#1]
When this is released, will I need an ESP8266 for this to work?

**Comment by HomeKidd** [comment]
No, its made for an existing LED controller named [MagicHome](https://github.com/HomeKidd/HomeKit-MagicHome-LED-controller-Elgato-Eve-Light-Strip/blob/master/README.md)!

**Comment by ChopsKingsland** [comment]
I already have a MagicHome controller, so will it just add the MagicHome app to HomeKit?

**Comment by HomeKidd** [comment]
No, you have to erase the stock MagicHome firmware, so after that you cannot control it via the stock app anymore. But the new firmware (my version) will support Home app natively so after the modification you can control it via HomeKit **only**.

**Comment by ChopsKingsland** [comment]
Ohhhh ok. How would I flash new firmware?
